### ISSUE TITLE
雙和打的轉換

### ISSUE THREAD

**Issue by joycewei** [karateboy/tights#1]
例如 30雙 = 2.5打
但是工廠習慣寫成 2.05
這有辦法改嗎?

**Comment by karateboy** [comment]
可以，在定型，整理都可以用2.05或的輸入發生

**Comment by joycewei** [comment]
但是在 "處理中漂染單" 會出現 2.5耶

**Comment by karateboy** [comment]
我知道了. 問題出在排定工作時，的單位是雙，不是打. 這我會改過來

**Comment by karateboy** [comment]
screen shot

**Comment by karateboy** [comment]
![16444019_1374410969297116_664662694_o](https://cloud.githubusercontent.com/assets/1067042/22546738/38dc974e-e979-11e6-9c91-9c6032013004.png)

**Comment by karateboy** [comment]
![image](https://cloud.githubusercontent.com/assets/1067042/22547221/a7892156-e97b-11e6-9c47-92979b32cade.png)

**Comment by karateboy** [comment]
fixed
