### ISSUE TITLE
漂染精煉劑 染鍋 用按的

### ISSUE THREAD

**Issue by karateboy** [karateboy/tights#12]
染鍋: 美1,美2,美3,美4,泳1,泳2,泳3,泳4,泳5,壓小,壓中,壓大,義,樣1,樣2

精煉劑: LYS, 環保, 特用, 其他

均染: 一般, PAM

**Comment by karateboy** [comment]
fixed

**Comment by joycewei** [comment]
阿那個格式 因為染鍋的關係整個變的怪怪的
染鍋可以 例如並排嗎?
