### ISSUE TITLE
複製訂單之後 新增 "編輯"功能?

### ISSUE THREAD

**Issue by joycewei** [karateboy/tights#16]
注意事項的地方
只有"刪除" 重打 
能不能增加 "編輯" ?所以那個欄位不會消失但是我可以更改細項?

![default](https://cloud.githubusercontent.com/assets/25497399/22768709/d24eb444-eebe-11e6-9da1-7c3505965b19.png)

**Comment by karateboy** [comment]
變成文字輸入方塊, 修改後. "更新"即可
