### ISSUE TITLE
漂染單

### ISSUE THREAD

**Issue by joycewei** [karateboy/tights#18]
數量 "優/預定"  部分能否也用"打"顯示?
另外 印出漂染工作單時, 打數的"雙數"部分會不見
例如 "22.07" 只會顯示 22
加總時也會把後面雙數省略

還有因為我把打數寫錯了
能不能修改? (例如 漂染卡 000001)
不然重改就會採用新的序號

![default](https://cloud.githubusercontent.com/assets/25497399/22778447/e7f26146-eef1-11e6-8a21-0e8c47b26067.png)

**Comment by karateboy** [comment]
打數已經修好...
我是建議不要修改, 直接刪掉重新產生新的就好.
因為要修改要考慮的東西很多, 比方說你要新增流動卡? 改數量? 刪掉流動卡? 修改會不會有其他的副作用...有點複雜, 但實際上用的機會卻不多. 

至於序號多產生一個新的也沒關係, 因為這是用印表機印.
