### ISSUE TITLE
進度部分能否顯示"打"

### ISSUE THREAD

**Issue by joycewei** [karateboy/tights#19]
![default](https://cloud.githubusercontent.com/assets/25497399/22821255/446c9fae-efb5-11e6-8d13-1a22e84c52fb.png)

**Comment by karateboy** [comment]
fixed

**Comment by joycewei** [comment]
在訂單頁面進度表還是看到雙?
![default](https://cloud.githubusercontent.com/assets/25497399/23303188/99b359b2-facd-11e6-8edc-094003fd32e1.png)

**Comment by joycewei** [comment]
在"我的訂單"地方看進度還是看到"雙"
能否變成"打"?

**Comment by karateboy** [comment]
好....有找到新問題可以開新的issue, 或者把原本的issue重新打開, 這樣比較容易追蹤

**Comment by karateboy** [comment]
fixed in 1.0.9

**Comment by joycewei** [comment]
好像還是一樣耶
在訂單進度部分

**Comment by karateboy** [comment]
因為修在1.09版本, 目前你們的版本是1.08

**Comment by karateboy** [comment]
也修正了
