### ISSUE TITLE
漂染工作單更新

### ISSUE THREAD

**Issue by joycewei** [karateboy/tights#21]
1 能否在 染色藥劑 增加 "黑色"欄位 以及  "其他" 欄位 (可以填入名稱和數字)
2.後處理程序 加入"溫度'欄位 (最好放在"時間"欄位上面; 如同其他格子的溫度,時間排列方式)
3.後處理程序 和 染色程序 空白處加欄位可自行填入其他的東西
4. 烘乾  能否加入"機台" 欄位, followed by 溫度, 時間

![default](https://cloud.githubusercontent.com/assets/25497399/23016443/86a4e442-f471-11e6-881c-32fe51366444.png)

**Comment by karateboy** [comment]
增加欄位沒問題...

但先前說匯出Excel格式的查詢我建議是不要
這等於把系統弄回以前你們單機作業的模式. 
我的建議是:
1. 開放資料庫的權限, 你可以利用Power BI或者其他NoSQL的資料庫查詢工具, 產生報表
2. 我幫你們產生客製化的報表. (不在這次工作範圍, 看是下階段, 或列入維護工作)

**Comment by karateboy** [comment]
Fixed in 1.0.7

**Comment by joycewei** [comment]
1.能增加欄位嗎？
增加＂黑＂和3個空白？所以能有三行

**Comment by karateboy** [comment]
黑和自己填的染色劑, 數量不是已經加了?
