### ISSUE TITLE
訂單修改

### ISSUE THREAD

**Issue by joycewei** [karateboy/tights#22]
sales說 這個顏色尺寸部分 能不能編輯或修改因為她打錯了想修改沒辦法
還有訂單能不能增加刪除功能?因為打錯了

![issue](https://cloud.githubusercontent.com/assets/25497399/23114123/16633b5c-f778-11e6-8e75-78bf370e6ed7.jpg)

**Comment by karateboy** [comment]
Fixed in 1.0.7
