### ISSUE TITLE
進度無法顯示在"查詢流動卡"中

### ISSUE THREAD

**Issue by joycewei** [karateboy/tights#23]
在整理課輸入了進度 在日報表中可以顯示

![default](https://cloud.githubusercontent.com/assets/25497399/23303955/20df7eda-fad2-11e6-9d4b-8920efaf72ee.png)

舉例拿 AA124910
到"生產排程", "查詢流動卡"
輸入 AA124910之後顯示無誤
![default](https://cloud.githubusercontent.com/assets/25497399/23304020/8cf4a230-fad2-11e6-998a-888e009471bd.png)

但是假設再查另一張流動卡 例如AA124909
結果內容完全跟AA124910一樣
![default](https://cloud.githubusercontent.com/assets/25497399/23304047/b2fb777e-fad2-11e6-804b-7eb6d7ac3a0e.png)

如果我用 "查詢訂單"的方式
基本上每個流動卡顯示出的進度部分都一樣 是上一筆資料 (也就是AA124910的進度)
大概就是在抓進度的地方有bug

**Comment by karateboy** [comment]
了解....這應該是某個快取的bug
回國後馬上幫你修

**Comment by karateboy** [comment]
我試了一下...好像測不出這個問題.
你這周人會在台北嗎? 我可以當面跟你討論一下

**Comment by karateboy** [comment]
fixed in 1.08

**Comment by karateboy** [comment]
確認沒問題, 請關掉
