### ISSUE TITLE
漂染單工作進度顯示不一致

### ISSUE THREAD

**Issue by joycewei** [karateboy/tights#24]
查詢漂染單時例如 000031 
會出現 "結束"  但是內容卻是 "處理中"

而且這張漂染單會被從 "處理中漂染單"list中移除

我記得我還沒按過 "結束工作卡"

![default](https://cloud.githubusercontent.com/assets/25497399/23447226/69778394-fe84-11e6-9f63-65a7356ddf3b.png)

**Comment by karateboy** [comment]
漂染單是白單, 流動卡是綠卡. 漂染結束後, (漂染那邊刷條碼結束)
綠卡還是會繼續處理. 直到整理課結束工作卡

**Comment by joycewei** [comment]
了解!
