### ISSUE TITLE
訂單可印出嗎?可加總嗎?

### ISSUE THREAD

**Issue by joycewei** [karateboy/tights#25]
sales希望訂單是否可以列印出來? 工廠需要紙本

另外同一客戶的單子 能否加總?

**Comment by karateboy** [comment]
甚麼工作有錢都可以呀～
訂單有列印出來有參考的格式嗎？
加總是兩三張訂單合併嗎？

**Comment by joycewei** [comment]
現場人員還是需要紙本

加總可能是 例如訂單xxx至xxx
或是某個月份的某個客人

**Comment by karateboy** [comment]
我找不到之前紙本的內容
可否拍張照片給我?

另外, 第一期的計畫, 功能就加到這為止.
如果有其他新的需求, 下一期再進行.

**Comment by karateboy** [comment]
確認沒問題就把issue關掉 🗡

**Comment by joycewei** [comment]
列印出來的格式怪怪的
跟原本不同
另外希望能夠一頁就好

**Comment by karateboy** [comment]
可以附上一張範例pdf嗎? 我自己建立的測試資料, 看不出問題...

**Comment by joycewei** [comment]
[訂單20170051.pdf](https://github.com/karateboy/tights/files/864058/20170051.pdf)
[訂單20170185.pdf](https://github.com/karateboy/tights/files/864060/20170185.pdf)

**Comment by karateboy** [comment]
看到兩個問題, 
1.部門要顯示中文, 而不是程式內部用的英文代碼
2. 列印的格式要壓縮成一行? 或改成兩列?

**Comment by joycewei** [comment]
能不能改成兩列?比較容易讀也省版面
(請參照原本格式)

**Comment by karateboy** [comment]
好

**Comment by karateboy** [comment]
已修正, 安排時間更新
