### ISSUE TITLE
列印流動卡標籤

### ISSUE THREAD

**Issue by joycewei** [karateboy/tights#26]
我想定一批上面印有條碼的綠色流動卡
所以能不能把 流動卡標籤上的條碼部分拿掉所以可以擠的下一張小標籤?
上次那個新增的"優'會跑到第二張標籤 所以
[工作卡標籤 (2).pdf](https://github.com/karateboy/tights/files/866770/2.pdf)
拿掉好了

另外流動卡標籤上面的數量有誤
每張都是"600" 而不是分別的數量 "50" "50" "50"

**Comment by karateboy** [comment]
需要把字體變小...這樣就可以塞到整個標籤嗎?
