### ISSUE TITLE
漂染工作單格式

### ISSUE THREAD

**Issue by joycewei** [karateboy/tights#28]
漂染工作單格式修改
1. 例如這張  因為包襪品項太多 會變成兩頁
2. 下面拉量尺寸的部分 我發現 你把同尺寸的合併了,但因為是不同種類的襪子所以還是得分開
3.烘乾後面增加 機台欄位
[%E6%BC%82%E6%9F%93000090.pdf](https://github.com/karateboy/tights/files/978094/E6.BC.82.E6.9F.93000090.pdf)

我修改的如下
這樣應該可以塞的下
[SKMBT_C36417050512130.pdf](https://github.com/karateboy/tights/files/978106/SKMBT_C36417050512130.pdf)

**Comment by karateboy** [comment]
Fixed in 1.0.14
