### ISSUE TITLE
定型課日報表

### ISSUE THREAD

**Issue by joycewei** [karateboy/tights#29]
請新增下面四欄:  

客戶編碼
工廠代號
顏色
尺寸

**Comment by karateboy** [comment]
Fixed in 1.0.14

**Comment by joycewei** [comment]
報表格式怪怪的
[定型報表0705_0708.xlsx](https://github.com/karateboy/tights/files/1130328/0705_0708.xlsx)

**Comment by karateboy** [comment]
fixed in 1.0.18

**Comment by joycewei** [comment]
還是怪怪的

另外Excel 2003版本會跑不出來
是我這邊需要更新嗎?還是你可以降版本?

[%E5%AE%9A%E5%9E%8B%E5%A0%B1%E8%A1%A80704_0705.xlsx](https://github.com/karateboy/tights/files/1137688/E5.AE.9A.E5.9E.8B.E5.A0.B1.E8.A1.A80704_0705.xlsx)

**Comment by karateboy** [comment]
我這邊開起來是正常的. 
![image](https://user-images.githubusercontent.com/1067042/28050785-5338f11a-6632-11e7-8d1d-c398984a8ad6.png)

**Comment by karateboy** [comment]
只是查看沒有要編輯Excel, 可以下載免費的Excel Viewer
[https://www.microsoft.com/zh-tw/download/details.aspx?id=10](url)

**Comment by karateboy** [comment]
fixed 逗號和句號都支援

**Comment by karateboy** [comment]
fixed
