### ISSUE TITLE
漂染工作不能更新

### ISSUE THREAD

**Issue by joycewei** [karateboy/tights#31]
輸入 "精練劑"的地方會產生錯誤訊息400
如果只有選擇 精練劑種類 不輸數字 可以存檔
但是一旦輸入過數字 就會出現錯誤
就算再把數字刪掉 *但是highlight在, 一樣會有錯誤不能再存檔

![default](https://cloud.githubusercontent.com/assets/25497399/26713029/ef5d86aa-479c-11e7-8dc9-413add846bbf.png)

**Comment by joycewei** [comment]
有發現不只這
大部分的格子在輸入後，按＂更新＂時會出現 error

**Comment by karateboy** [comment]
Fixed in 1.0.16
