### ISSUE TITLE
漂染工作單格式

### ISSUE THREAD

**Issue by joycewei** [karateboy/tights#32]
1. 少了原來的 包襪人員（空白）、包襪日期 （空白）丶備註（代入）這三個cell

2. 條碼欄位可以變窄一點  太大了 (剛好可以多一欄放 包襪人員, 日期,備註)

3. "顏色" 的字型請放大一點,師傅說老花眼看不清楚  > <

4. "染色程序"的第二次 "溫度" 應該是 "時間: ___分鐘" 
 和 "後處理程序"的 "柔軟時間" 單位有誤 應該改成 "溫度:_____C"  
下面一欄 "時間:_______分鐘"  沒加上去

均染劑的欄位設計能改一下跟精練劑一樣嗎? 
i.e. 均染劑: _________kg 
(一般, PAM. 其他)
 

![default](https://user-images.githubusercontent.com/25497399/27026042-0f6972de-4f8f-11e7-8673-0036f5fcfbcf.png)
 
![default](https://user-images.githubusercontent.com/25497399/27026236-a74ea1e6-4f8f-11e7-91dd-4888cb66fc4a.png)

**Comment by karateboy** [comment]
fixed in 1.0.15
