### ISSUE TITLE
查詢訂單功能

### ISSUE THREAD

**Issue by joycewei** [karateboy/tights#34]
欄位請開放  不管大小寫都可以查得到
e.g. Capezio, CAPEZIO, capezio  如果不是跟當初key in 格式一模一樣會查不到

**Comment by karateboy** [comment]
除了訂單編號, 全都開放大小寫無分.
(大小寫無差, 會降低搜尋速度..)

**Comment by karateboy** [comment]
fixed in 1.0.15
