### ISSUE TITLE
列印工作標籤

### ISSUE THREAD

**Issue by joycewei** [karateboy/tights#42]
不要跳出 另存新檔

**Comment by karateboy** [comment]
無法在我的機器上 呈現這個問題...

**Comment by joycewei** [comment]
這可能是 瀏覽器設定的問題?

**Comment by karateboy** [comment]
應該是...你也可以在你的瀏覽器是看看....

**Comment by joycewei** [comment]
我試不出來
我把惠真電腦chrome更新了  看來是 在"每次存檔都要詢問位置"這裡 不勾選 應該就好
但是偏偏惠真的電腦上  "列印"工作卡的部分會直接存對應檔名後開啟,
 "列印漂染標籤"的部分就會跳出對話 問存那裏,檔名已存在是否要覆蓋,etc,
然後才會開啟檔案

很神奇吧!就算CHROME 跟電腦室小姐用一樣的最新版本    設定也一樣 結果卻不同 > <

**Comment by karateboy** [comment]
先close.
