### ISSUE TITLE
查詢訂單 加總%

### ISSUE THREAD

**Issue by joycewei** [karateboy/tights#45]
1. 查詢訂單後 顯示頁面上訂單的 總完成打數 和 完成打數/總需求(%)
2. 每張流動卡 進度(打): (生產中/已完成) 改成 " 進度(打):(生產中/已結束)"
損耗(雙) 改成  損耗百分比 (雙/雙)

![image](https://user-images.githubusercontent.com/25497399/27624263-816049e6-5c12-11e7-88fc-a5bb81746733.png)

**Comment by karateboy** [comment]
已修正
