### ISSUE TITLE
工作標籤格式

### ISSUE THREAD

**Issue by joycewei** [karateboy/tights#48]
我想把它改整齊一點的格式

[流動卡修改.pdf](https://github.com/karateboy/tights/files/1130405/default.pdf)

**Comment by karateboy** [comment]
除了中間...旁邊的撕下的小卡, 也要改成
日期
優
副
汙
破
不均
油
工號
備註
主管審核
?

**Comment by joycewei** [comment]
更新如下
謝謝
[修改流動卡_rev.pdf](https://github.com/karateboy/tights/files/1134903/_rev.pdf)

**Comment by karateboy** [comment]
fixed in 1.0.20

**Comment by joycewei** [comment]
課長反應 能不能
請在 "汙" 和 "破" 中間再加 "長短腳" 
右邊的小卡也加吧 這樣比較統一

謝謝!

**Comment by karateboy** [comment]
所有輸入也一併更改?

**Comment by joycewei** [comment]
紙本的部分:
日期
優
副
汙
長短
破
不均
油
工號


整理包裝的輸入部分
優
副
汙
長短
破
不均
油

**Comment by joycewei** [comment]
不好意思 課長有反應 "副"有兩種 麻煩你
紙本的部分 (除了左聯的白襪以外) 其他全部多加入 "副未包" 比較統一
 (定型卡的 "機台"欄位還是要保留)

日期
優
副
副未包
汙
長短
破
不均
油
工號

整理包裝的電腦輸入部分也改和上面一樣 
其他課的可以不用改變

**Comment by karateboy** [comment]
fixed
