### ISSUE TITLE
漂染單字型

### ISSUE THREAD

**Issue by joycewei** [karateboy/tights#50]
請把  訂單編號: "20170435" 和 出貨日: "2017-07-25"  字型變大 
老花看不太清楚 > <
能採取換行方式 所以字串不會再變兩行嗎?
然後跟條碼欄位一樣高度就好了 

訂單編號:
# 20170435  

出貨日:
# 2017-07-25

**Comment by karateboy** [comment]
我偷懶一點, 標題和字體都用粗體字...這樣ok吧?
[漂染000625 (6).pdf](https://github.com/karateboy/tights/files/1147432/000625.6.pdf)

**Comment by joycewei** [comment]
這樣條碼欄太大了
萬一很多張流動卡   就會又塞不下

**Comment by joycewei** [comment]
如果像這張漂染單  字型變大  塞的下嗎?
000752
000756
