### ISSUE TITLE
訂單不足量沒有進入排定工作

### ISSUE THREAD

**Issue by joycewei** [karateboy/tights#52]
訂單 20170316
白wht 需要20打, 生產21打卻只有19打優 
但是在 排定工作裏面卻找不到 無法開單

![default](https://user-images.githubusercontent.com/25497399/28526690-db88008c-70ba-11e7-95f6-483e0721dce0.png)
![default](https://user-images.githubusercontent.com/25497399/28526748-08a3c89e-70bb-11e7-8861-d605d7c55af0.png)
![default](https://user-images.githubusercontent.com/25497399/28526824-4797b90c-70bb-11e7-9b38-4205d771c1c4.png)

**Comment by karateboy** [comment]
該筆訂單已經結案了, 所以缺的部分也不會進入到"生產排程"中. 如果有需要可以"重啟"
![image](https://user-images.githubusercontent.com/1067042/28551956-c8f4217c-711d-11e7-8f99-1e1c6b51f64e.png)
