### ISSUE TITLE
複製訂單會變成 已結案

### ISSUE THREAD

**Issue by joycewei** [karateboy/tights#54]
當複製已結案的訂單要成立新訂單的時候
會直接變成 已結案訂單 而非新訂單
能改成 複製訂單的default是新訂單 嗎?

**Comment by karateboy** [comment]
ok...
現階段可以work around
把複製的訂單重啟...

**Comment by karateboy** [comment]
fixed in 1.0.23

**Comment by karateboy** [comment]
已經更新
