### ISSUE TITLE
流動卡一旦有人不小心輸入0, 就蓋不過去

### ISSUE THREAD

**Issue by karateboy** [karateboy/tights#55]

**Comment by joycewei** [comment]
備註
看來是 你上次說的會取歷史最小值 而不是最更新值
除了0也有發現 某張流動卡儘管最後優的數字更新了 卻一直記錄另外一個值 (非"0")

**Comment by karateboy** [comment]
Fixed. 演算法改為, 更新時若流動卡優大於現在的最小值, 則重新計算最小值.

**Comment by karateboy** [comment]
fixed
