### ISSUE TITLE
庫存 (想法)

### ISSUE THREAD

**Issue by joycewei** [karateboy/tights#58]
在 "排定工作"這頁
增加 "取自庫存"的功能 讓惠真開單的時候直接開庫存
庫存不產生條碼而是以 "來自庫存"字樣代替 ,數字直接加到"已完成"的量
所以不需要去結這張流動卡  本來就在已結束的狀態 
綠卡照樣印出  但是不交給白襪備襪,而是交給整理課和倉庫當作通知 
(所以倉庫會把這筆庫存找出來裝箱;整理課會把這筆從他所需的數量中扣掉)

input格式改成

訂單編號 | 預定交貨日 | 工廠代號 | 尺寸 | 已排定生產/需求量(打) |取自庫存/庫存量(打) |  排定生產(打) |取自庫存(打) |  條碼 | 

所以按下 "排定生產"以後,  取自庫存的部分
只會產出一張綠色流動卡 (沒有條碼)   
不會有白色工作單

*如果可以同時也排定生產和來自庫存更好
但來自庫存的數量一樣不能進到 白色漂染工作卡裡面 否則算襪重會有錯誤  
所以我想 也許分開來開單比較方便?

那還要在某個地方 把 "庫存數量"輸入
這個是不是能像是 把 "排定工作"的資料部分 開放輸入庫存?
例如希望 倉庫在每次出貨完後整理好庫存可以輸入

**Comment by karateboy** [comment]
來自庫存和排定生產分開沒問題,

另外就是在各生產課手頭的庫存...有結論了嗎?
有沒有打算弄成大水庫/小水庫的概念?

**Comment by joycewei** [comment]
基本上庫存應該只有一個
但是由於庫存的數字會一直更動  要每次出貨以後一個星期內才會有最新庫存量
所以其實在開單的時候 用的是上上次的庫存量
即便八月底有貨要出 也不能去拿目前庫存 因為已經預備給九月的單用...不過我想 如果我們可以維持這樣應該也還好
或是說 如果庫存水位是隨時Update的話  例如庫存還有剩 那八月這批貨也可以去拿庫存的來用

另外就是要增加讓整理課可以多打進去5%左右的量就好  也許可以進到庫存
不然反正他們會集中到倉庫  基本上就是等出貨完一次更新庫存量

這樣大概就是沒有大小水庫之分?

**Comment by joycewei** [comment]
庫存開單:
1. 在排定工作的地方出現庫存,一併開單, 然後顯示在綠卡"成品倉庫"欄位的 "優" 數量
2. 排定工作後庫存就先暫時扣掉了,等到倉庫確實取出庫存後刷卡完成庫存更新 
3. 整理包裝 的部分  流動卡也能輸入 '來自庫存", 輸入後即扣掉庫存 (不再經過倉庫)
4. 能建立一份 "來自庫存"的報表
