### ISSUE TITLE
修改流動卡

### ISSUE THREAD

**Issue by joycewei** [karateboy/tights#59]
流動卡 小聯單 ( 列印標籤)
定型卡欄位異動:  把"副未包"改成"襪頭"  其他不變

日期:
優:
副:
副未包: =>改成 "襪頭"
汙:
長短:
破:
不均:
油:
工號:
備註:
主管審核

**Comment by karateboy** [comment]
了解, 明天更新.

**Comment by karateboy** [comment]
1.0.23版

**Comment by karateboy** [comment]
已經更新

**Comment by joycewei** [comment]
不好意思 只有 "定型卡" 要改成"襪頭"
就是最右邊的小聯單改就好
其他都不要動

**Comment by joycewei** [comment]
整理課的 系統輸入部分
不需要 "襪頭"
而是要 "副未包"
麻煩請回復

至於定型課 就保留現在的改版

至於 定型的部分
