### ISSUE TITLE
顏色/尺寸用選的

### ISSUE THREAD

**Issue by karateboy** [karateboy/tights#6]

**Comment by joycewei** [comment]
尺寸: 
XS/S, S/M, M/L, L/XL, 2-6, 8-12, XXS, XS, SS, M, L, XL, XXL, M/S, T, A/B, C/D, A, B, C, D, E, 
XSml, Sml, Med, Lge, Xlge, Sml/Med, Lge/Xlge, ChSml, ChLge, Adult, ChSml/ChMed, ChMed/ChLge,
ChLge/ChXLge, 
0-6, 6-12, 12-24, 2T3T, 4T5T, 6-8

大概是這樣 但是還是要有可以自行填入的空間 因為客人編碼一直在改變 > <

顏色補分再給

**Comment by karateboy** [comment]
Fixed in 1.0.7
