### ISSUE TITLE
轉換漂染卡看不見漂染卡選項

### ISSUE THREAD

**Issue by joycewei** [karateboy/tights#60]
例如 流動卡號005828  想轉換到漂染卡001980
但是選單裡面看不見001972以後同色的漂染卡
也無法指定轉換到哪一張漂染卡

![default](https://user-images.githubusercontent.com/25497399/31760613-d9f170ca-b4e7-11e7-9b6c-83d7b5391815.png)

**Comment by karateboy** [comment]
已加上卷軸, 下次遇到也可先縮小螢幕顯示比例
