### ISSUE TITLE
增加漂染處理狀態

### ISSUE THREAD

**Issue by joycewei** [karateboy/tights#61]
1. 已出單
2. 白襪準備中
3. 漂染準備中
4. 已結束

處理中漂染單 -> 已開單(只要開單就算)- 白襪中(惠真印好scan後給白襪)-漂染等待中(惠真包好推去漂染前scan)-漂染中(漂染師傅已開始) -結束(漂染師傅結束)
----------------------------------------------------------------------------
在 查詢漂染單 頁面 新增 查詢 "訂單編號"

**Comment by karateboy** [comment]
除白襪中沒有
其他已經完成

**Comment by joycewei** [comment]
能否把功能改成 那個後SCAN會蓋掉新的SCAN ?

**Comment by joycewei** [comment]
希望建立表單 
有每天漂染的  1.表染單號 2.訂單號碼 3.打數 4.顏色

**Comment by joycewei** [comment]
後面scan會蓋掉前面的步驟
例如 "開始漂染"後 就算"送漂染課"忘了滴滴 狀態也會顯示成 漂染中

另外 只要流動卡 有更新   漂染單的狀態也顯示成 "已完成"
