### ISSUE TITLE
庫存

### ISSUE THREAD

**Issue by joycewei** [karateboy/tights#62]
工廠代號/顏色/尺寸 當作庫存(索引)

如果排定生產, 的項目在庫存中, 可以排定來自庫存.
排定工作時, 列印庫存卡

另外, 有介面輸入現有庫存

**Comment by joycewei** [comment]
BUG: 
1.排定生產 如果沒使用庫存  生產數量會顯示 NaN
2. 流動卡已經有排定庫存的量 ,但是如果在結束之前修改了庫存量  則 查詢庫存的時候  已經排定使用庫存的那張流動卡和排定量就不會顯示 好像歸零了   
但如果單獨去查詢那張流動卡又可以看到 來自庫存的數目


庫存輸入 能否用客人編號 對應到  工廠代號 
基本上會做庫存管理的應該也只有三家客戶

**Comment by karateboy** [comment]
1. 已修正
2. 測不出這個問題.
3. 我仔細想了一下, 整理課去庫存那邊拿襪子, 補足"優" 其實是很有問題的.
    理由如下:
    惠珍排定生產的時候就會多排, 整理課如果拿庫存把優捕到滿, 其實是會太多.
    與其如此, 不如整理課就不用補庫存了. 反正最後惠珍會看到到底夠還是不夠
   如果不夠, 她再排流動卡去生產, 或者是存庫存補足就好.

每個人看到的流動卡其實只是局部, 惠珍看到的才是滿足訂單的全局. 所以最好的方式還是, 不管庫存還是整理課都不要自作聰明去補, 讓惠珍看到沒法滿足訂單來處理才是.

**Comment by joycewei** [comment]
需要修正 希望輸入庫存用
1. scan barcode (用手機或平板)
2. barcode 對應到每一個品項的建立
