### ISSUE TITLE
漂染工作單增加欄位

### ISSUE THREAD

**Issue by joycewei** [karateboy/tights#63]
在＂編織批號＂（不是＂編織編號＂）下增加＂品牌＂（自動代入）
![325ebf8e-fe77-4085-b1b7-195e0e175bdf](https://user-images.githubusercontent.com/25497399/32826564-ddab94e2-ca23-11e7-9ede-9c5097f23c1d.jpeg)

**Comment by karateboy** [comment]
fixed
