### ISSUE TITLE
訂單修改功能

### ISSUE THREAD

**Issue by joycewei** [karateboy/tights#64]
用複製訂單以後
不需要的品項如何刪除？
我記得之前有刪除鍵？
例如黑色和上面那個品項

![29dd5dcd-3dd1-4deb-ac2a-07a56448c7f6](https://user-images.githubusercontent.com/25497399/32870478-08e0ae20-cab7-11e7-8256-59a89844f365.jpeg)

**Comment by karateboy** [comment]
現有訂單不開放刪除訂單細項, 因為會有"已經排定的流動卡"的問題
