### ISSUE TITLE
新增備註

### ISSUE THREAD

**Issue by joycewei** [karateboy/tights#66]
希望在排定工作輸入的 "備註" 除了出現在漂染工作單上(白單)
也能出現在 綠卡上  (綠卡我看輸入部分不要再增加備註欄位了)
建議放在  條碼右邊那一堆空白的部分  

![default](https://user-images.githubusercontent.com/25497399/33873230-30d8b190-df55-11e7-88ee-13751699305f.JPG)

條碼下面那串數字有機會放大一點點嗎? 把條碼縮扁一點?字大一點?但是不要影響版面了

**Comment by karateboy** [comment]
[工作卡標籤.pdf](https://github.com/karateboy/tights/files/1584656/default.pdf)

這樣ok嗎? 沒有問題就比照修改
