### ISSUE TITLE
庫存數為負

### ISSUE THREAD

**Issue by joycewei** [karateboy/tights#72]
若是在流動卡輸入了使用庫存量 超過庫存  
則庫存數變成負數  (而且在 "查詢庫存"的時候看不見負值,要去"排定工作"的地方才會出現)
當負值的時候就不能再排定生產了 

我解決之道是把庫存更新為0或是其他正值 但是沒用 
後來把品項刪除 先排定生產以後 再重新增庫存
不過目前系統沒有這個了 可能要自己試一下
我們找一個不影響目前生產的訂單試試看

**Comment by karateboy** [comment]
問題應該找到了 禮拜一可以試看看
